others = {"i'm" : "i am",
"im" : "i am",
"y" : "you",
"u": "you",
"wnt": "want",
"r": "are",
"it's" : "its",
"can't" : "can not",
"yrs" : "yours",
"whr" : "where",
"don't" : "do not",
'dont': 'do not',
"hahaha" : "haha",
"hahahaha" : "haha",
"bbye" : "bye",
"bf" : "boyfriend",
"sry" : "sorry",
"okk" : "ok",
"bcz" : "because",
"cuz" : "because",
'coz': "because",
'cos': 'because',
'cause': 'because',
"knw" : "know",
"dn" : "do not",
"awesom" : "awesome",
"yayy" : "yay",
"coll": 'call',
'scool': 'shool',
'n': 'and',
'pls': 'please',
'pik': 'picture',
'pic': 'picture',
'gd': 'good',
'evng': 'evening',
'(':'',
')':'',
'<':'',
'>':'',
'[':'',
']':'',
'.':'',
',':'',
'-':'',
',':'',
'~': '',
'bfr': 'before',
'bff': 'best friends forever',
'bffs': 'best friends forever',
'shud': 'should',
'gf': 'girlfriend',
'ur': 'your',
'*':'',
'opps': 'oops',
'_':'',
'__':''
}