others = {"i'm" : "i am",
"im" : "i am",
"y" : "you",
"it's" : "its",
"can't" : "can not",
"yrs" : "yours",
"whr" : "where",
"don't" : "do not",
"hahaha" : "haha",
"hahahaha" : "haha",
"bbye" : "bye",
"bf" : "boyfriend",
"sry" : "sorry",
"okk" : "ok",
"bcz" : "because",
"cuz" : "because",
"knw" : "know",
"dn" : "do not",
"awesom" : "awesome",
"yayy" : "yay"}